version: 2
jobs:
  build:
    docker:
            - image: python:3.6.8

    steps:
      - checkout
        
      - add_ssh_keys:
          fingerprints:
            - "7a:73:03:32:a7:39:aa:21:8f:0b:93:46:68:c2:90:96"
            - "43:86:92:d0:30:5e:39:09:aa:73:be:50:b1:fc:8e:7d"  

      - run:
          name: tree
          command: python -c "circleci-test/tests/test_tree.py"

      - run:
          name: content
          command: python -c "circleci-test/tests/test_tree.py"
