version: 2
jobs:
  build:
    docker:
            - image: python:3.6.8

    steps:
      - checkout

      - run:
          name: tree
          command: python -c "circleci-test/tests/test_tree.py"

      - run:
          name: content
          command: python -c "circleci-test/tests/test_tree.py"
